#! /usr/bin/python

import qt
import sys
import numarray

print sys.version          # Python version
print qt.qVersion()        # Qt version
print numarray.__version__ # version of numarray module
# print qt.__version__     # version of qt module (can't be determined automatically!)