#! /usr/bin/env python
# -*- coding: UTF-8 -*-

import qt
import sys
from mainwindow import *

#import psyco
#psyco.full()

def entryPoint():
	app = qt.QApplication(sys.argv)
	# for e in QStyleFactory.keys(): print e
	mw = MainWindow()
	app.setMainWidget(mw)
	mw.show()
	sys.exit(app.exec_loop())

entryPoint()                  # comment out this line to apply profileit.py
