%.png: %.svg
	convert $< $@
	
targets= \
 aggregation.png \
 composition.png \
 generalization.png \
 association.png \
 relation.png \
 dependency.png \
 implements.png \
 class1.png \
 class2.png \
 class3.png \
 noicon.png

all: $(targets) 

clean:
	rm -rf *.png
