#! /usr/bin/python
# -*- coding: UTF-8 -*-

from konzeptserver import *
from xmltokensource import *
from indentsink import *

serv = KonzeptServer()
serv.readXml(XmlTokenSource(file("konzept_server.xml")))
serv.run()
serv.writeXml(IndentSink(file("konzept_server.xml", 'w')))
