#!/usr/bin/python
# -*- coding: UTF-8 -*-

from qt import *

def decodeEventType(typeNum):
	typeToStrMap = {
		QEvent.None: "None",
		QEvent.Timer: "Timer",
		QEvent.MouseButtonPress: "MouseButtonPress",
		QEvent.MouseButtonRelease: "",
		QEvent.MouseButtonDblClick: "",
		QEvent.MouseMove: "MouseMove",
		QEvent.KeyPress: "KeyPress",
		QEvent.KeyRelease: "KeyRelease",
		QEvent.FocusIn: "FocusIn",
		QEvent.FocusOut: "FocusOut",
		QEvent.Enter: "Enter",
		QEvent.Leave: "Leave",
		QEvent.Paint: "Paint",
		QEvent.Move: "Move",
		QEvent.Resize: "Resize",
		QEvent.Create: "Create",
		QEvent.Destroy: "Destroy",
		QEvent.Show: "Show",
		QEvent.Hide: "Hide",
		QEvent.Close: "Close",
		QEvent.Quit: "Quit",
		QEvent.Reparent: "Reparent",
		QEvent.ShowMinimized: "ShowMinimized",
		QEvent.ShowNormal: "ShowNormal",
		QEvent.WindowActivate: "WindowActivate",
		QEvent.WindowDeactivate: "WindowDeactivate",
		QEvent.ShowToParent: "ShowToParent",
		QEvent.HideToParent: "HideToParent",
		QEvent.ShowMaximized: "ShowMaximized",
		QEvent.ShowFullScreen: "ShowFullScreen",
		QEvent.Accel: "Accel",
		QEvent.Wheel: "Wheel",
		QEvent.AccelAvailable: "AccelAvailable",
		QEvent.CaptionChange: "CaptionChange",
		QEvent.IconChange: "IconChange",
		QEvent.ParentFontChange: "ParentFontChange",
		QEvent.ApplicationFontChange: "ApplicationFontChange",
		QEvent.ParentPaletteChange: "ParentPaletteChange",
		QEvent.ApplicationPaletteChange: "ApplicationPaletteChange",
		QEvent.PaletteChange: "PaletteChange",
		QEvent.Clipboard: "Clipboard",
		QEvent.Speech: "Speech",
		QEvent.SockAct: "SockAct",
		QEvent.AccelOverride: "AccelOverride",
		QEvent.DeferredDelete: "DeferredDelete",
		QEvent.DragEnter: "DragEnter",
		QEvent.DragMove: "DragMove",
		QEvent.DragLeave: "DragLeave",
		QEvent.Drop: "Drop",
		QEvent.DragResponse: "DragResponse",
		QEvent.ChildInserted: "ChildInserted",
		QEvent.ChildRemoved: "ChildRemoved",
		QEvent.LayoutHint: "LayoutHint",
		QEvent.ShowWindowRequest: "ShowWindowRequest",
		QEvent.ActivateControl: "ActivateControl",
		QEvent.DeactivateControl: "DeactivateControl",
		QEvent.ContextMenu: "ContextMenu",
		QEvent.IMStart: "IMStart",
		QEvent.IMCompose: "IMCompose",
		QEvent.IMEnd: "IMEnd",
		QEvent.Accessibility: "Accessibility",
		QEvent.TabletMove: "TabletMove",
		QEvent.LocaleChange: "LocaleChange",
		QEvent.LanguageChange: "LanguageChange",
		QEvent.LayoutDirectionChange: "LayoutDirectionChange",
		QEvent.Style: "Style",
		QEvent.TabletPress: "TabletPress",
		QEvent.TabletRelease: "TabletRelease",
		QEvent.User: "User",
		QEvent.MaxUser: "MaxUser"
	}

	if typeNum in typeToStrMap:
		return typeToStrMap[typeNum]
	else:
		return "Unknown"

